en:
  errors:
    user:
      not_found: "User doesn't exist"
